version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dukcapil-brebes
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      - ENV=production
    restart: always
    volumes:
      - .:/app
    # Uncomment kalau lo pake env file
    # env_file:
    #   - .env
